web deploy list images with no args

diff --git a/host/assets/jsbatch/srv/home/uwscli/bin/web-deploy b/host/assets/jsbatch/srv/home/uwscli/bin/web-deploy
--- a/host/assets/jsbatch/srv/home/uwscli/bin/web-deploy
+++ b/host/assets/jsbatch/srv/home/uwscli/bin/web-deploy
@@ -13,14 +13,14 @@ deploy() {
 	uwsnq /srv/uws/deploy/cli/meteor-deploy.sh "amy-${1}" web "${2}"
 }
 
-if test "${region}" != 'east' && test "${region}" != 'west'; then
-	echo "invalid amy region: ${region}" >&2
-	exit 1
-fi
-
 if test "X${release}" = 'X'; then
 	list_images
 	exit 0
+fi
+
+if test "${region}" != 'east' && test "${region}" != 'west'; then
+	echo "invalid amy region: ${region}" >&2
+	exit 1
 fi
 
 case "${release}" in
